pipeline {
  agent any

  environment {
    IMAGE_NAME = "quangtienngucode/blog-cv"
    IMAGE_TAG = "${BUILD_NUMBER}"
    SCANNER_HOME = tool "sonar-scanner"
  }

  stages {
    stage("Git Checkout") {
      steps {
        git branch: "main", url: "https://github.com/quangtienngucode/personal-blog-cv.git"
      }
    }

    stage("Install Dependencies") {
      steps {
        dir("personal-blog-cv") {
          sh "npm ci"
        }
      }
    }

    stage("Lint") {
      steps {
        dir("personal-blog-cv") {
          sh "npm run lint"
        }
      }
    }

    stage("Typecheck") {
      steps {
        dir("personal-blog-cv") {
          sh "npm run typecheck"
        }
      }
    }

    stage("Build App") {
      steps {
        dir("personal-blog-cv") {
          sh "npm run build"
        }
      }
    }

    stage("Trivy FS Scan") {
      steps {
        dir("personal-blog-cv") {
          sh "trivy fs . --format table -o fs.html"
        }
      }
    }

    stage("SonarQube Analysis") {
      steps {
        dir("personal-blog-cv") {
          withSonarQubeEnv("sonarqubeServer") {
            sh "$SCANNER_HOME/bin/sonar-scanner"
          }
        }
      }
    }

    stage("Docker Build") {
      steps {
        dir("personal-blog-cv") {
          sh "docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest ."
        }
      }
    }

    stage("Trivy Image Scan") {
      steps {
        sh "trivy image --format table -o image.html $IMAGE_NAME:$IMAGE_TAG"
      }
    }

    stage("Docker Push") {
      steps {
        withDockerRegistry(credentialsId: "dockerhub-cred", url: "https://index.docker.io/v1/") {
          sh "docker push $IMAGE_NAME:$IMAGE_TAG"
          sh "docker push $IMAGE_NAME:latest"
        }
      }
    }

    stage("K8s Deploy") {
      steps {
        withKubeConfig(credentialsId: "eks-token") {
          sh "kubectl apply -f k8s/deployment-service.yml"
          sh "kubectl rollout restart deployment/blog-cv -n webapps"
        }
      }
    }

    stage("K8s Verify") {
      steps {
        withKubeConfig(credentialsId: "eks-token") {
          sh "kubectl rollout status deployment/blog-cv -n webapps"
          sh "kubectl get svc -n webapps"
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: "personal-blog-cv/fs.html,image.html", allowEmptyArchive: true
    }
  }
}
